### ISSUE TITLE
Высокоуровневые требования

### ISSUE THREAD

**Issue by laiola** [Likemilk99/HomeLibrarian#13]
Бизнес-требования (Business Requirements) – определяют высокоуровневые цели
организации или клиента (потребителя) – заказчика разрабатываемого программного
обеспечения.

**Comment by laiola** [comment]
https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BA_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%BD%D0%BE%D0%BC%D1%83_%D0%BE%D0%B1%D0%B5%D1%81%D0%BF%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D1%8E

**Comment by Likemilk99** [comment]
![image](https://cloud.githubusercontent.com/assets/14221341/13086006/1d159354-d4f2-11e5-92e1-fd276e837c7c.png)

**Comment by Likemilk99** [comment]
![image](https://cloud.githubusercontent.com/assets/14221341/13086466/66a1228e-d4f4-11e5-8653-1c2fedc745c9.png)
